export const clientInterviewTypes = [
  { type: "FOLLOW_UP", label: "Follow Up", color: "#F97316" },
  { type: "PHONE_SCREEN", label: "Phone Screen", color: "#EAB308" },
  { type: "ON_SITE", label: "On Site", color: "#10B981" },
  { type: "VIDEO_INTERVIEW", label: "Video Interview", color: "#6366F1" },
  { type: "INTERVIEW", label: "Interview", color: "#64748B" },
  { type: "ASSESSMENT", label: "Assessment", color: "#EC4899" },
  { type: "TECHNICAL", label: "Technical", color: "#9333EA" },
  { type: "PANEL", label: "Panel", color: "#3B82F6" },
  { type: "FINAL_ROUND", label: "Final Round", color: "#EF4444" },
  { type: "OFFER_EXTENDED", label: "Offer Extended", color: "#16A34A" },
  { type: "OFFER_ACCEPTED", label: "Offer Accepted", color: "#14B8A6" },
  { type: "OFFER_REJECTED", label: "Offer Rejected", color: "#DC2626" },
  { type: "REJECTION", label: "Rejection", color: "#6B7280" },
  { type: "CONTRACT_SIGNED", label: "Contract Signed", color: "#059669" },
  { type: "SALARY_NEGOTIATION", label: "Salary Negotiation", color: "#D97706" },
  { type: "FINAL_DECISION", label: "Final Decision", color: "#7C3AED" },
  { type: "PRE_SCREENING", label: "Pre-Screening", color: "#60A5FA" },
  { type: "GROUP_INTERVIEW", label: "Group Interview", color: "#06B6D4" },
  { type: "REFERENCE_CHECK", label: "Reference Check", color: "#84CC16" },
  { type: "TRIAL_PERIOD", label: "Trial Period", color: "#DB2777" },
  { type: "FINAL_OFFER", label: "Final Offer", color: "#0D9488" },
  { type: "OFFER_WITHDRAWN", label: "Offer Withdrawn", color: "#9CA3AF" },
  { type: "NEGOTIATION_PHASE", label: "Negotiation Phase", color: "#CA8A04" },
  {
    type: "ADDITIONAL_DOCS_REQUIRED",
    label: "Additional Docs Required",
    color: "#EA580C",
  },
  { type: "NO_SHOW", label: "No Show", color: "#B91C1C" },
  { type: "CANDIDATE_WITHDREW", label: "Candidate Withdrew", color: "#0F766E" },
  { type: "HIRING_FREEZE", label: "Hiring Freeze", color: "#6D28D9" },
  {
    type: "TAKE_HOME_ASSESSMENT",
    label: "Take Home Assessment",
    color: "#4F46E5",
  },
];