export const clientInterviewTypes = [
  { type: "FOLLOW_UP", label: "Follow Up", color: "bg-orange-400" },
  { type: "PHONE_SCREEN", label: "Phone Screen", color: "bg-yellow-400" },
  { type: "ON_SITE", label: "On Site", color: "bg-green-400" },
  { type: "VIDEO_INTERVIEW", label: "Video Interview", color: "bg-indigo-400" },
  { type: "INTERVIEW", label: "Interview", color: "bg-slate-400" },
  { type: "ASSESSMENT", label: "Assessment", color: "bg-pink-400" },
  { type: "TECHNICAL", label: "Technical", color: "bg-purple-400" },
  { type: "PANEL", label: "Panel", color: "bg-blue-400" },
  { type: "FINAL_ROUND", label: "Final Round", color: "bg-red-400" },
  { type: "OFFER_EXTENDED", label: "Offer Extended", color: "bg-green-500" },
  { type: "OFFER_ACCEPTED", label: "Offer Accepted", color: "bg-teal-500" },
  { type: "OFFER_REJECTED", label: "Offer Rejected", color: "bg-red-500" },
  { type: "REJECTION", label: "Rejection", color: "bg-gray-500" },
  {
    type: "CONTRACT_SIGNED",
    label: "Contract Signed",
    color: "bg-emerald-500",
  },
  {
    type: "SALARY_NEGOTIATION",
    label: "Salary Negotiation",
    color: "bg-amber-400",
  },
  { type: "FINAL_DECISION", label: "Final Decision", color: "bg-purple-500" },
  { type: "PRE_SCREENING", label: "Pre-Screening", color: "bg-blue-300" },
  { type: "GROUP_INTERVIEW", label: "Group Interview", color: "bg-cyan-500" },
  { type: "REFERENCE_CHECK", label: "Reference Check", color: "bg-lime-500" },
  { type: "TRIAL_PERIOD", label: "Trial Period", color: "bg-pink-500" },
  { type: "FINAL_OFFER", label: "Final Offer", color: "bg-teal-600" },
  { type: "OFFER_WITHDRAWN", label: "Offer Withdrawn", color: "bg-gray-400" },
  {
    type: "NEGOTIATION_PHASE",
    label: "Negotiation Phase",
    color: "bg-yellow-500",
  },
  {
    type: "ADDITIONAL_DOCS_REQUIRED",
    label: "Additional Docs Required",
    color: "bg-orange-500",
  },
  { type: "NO_SHOW", label: "No Show", color: "bg-red-600" },
  {
    type: "CANDIDATE_WITHDREW",
    label: "Candidate Withdrew",
    color: "bg-teal-700",
  },
  { type: "HIRING_FREEZE", label: "Hiring Freeze", color: "bg-purple-700" },
  {
    type: "TAKE_HOME_ASSESSMENT",
    label: "Take Home Assessment",
    color: "bg-indigo-600",
  },
];
