export const industryKeywords = [
  // **E-commerce & Retail**
  "E-commerce",
  "Online Retail",
  "Retail",
  "Consumer Goods",
  "Direct-to-Consumer",
  "Fashion Retail",
  "Grocery Retail",
  "Luxury Goods",
  "Apparel",
  "Food Delivery",
  "Beauty Products",
  "Health and Wellness Products",
  "Consumer Electronics",
  "Food and Beverage Retail",
  "Pet Products",
  "Home Decor",
  "Toys and Games",
  "Electronics Retail",
  "Subscription Boxes",
  "Marketplace",
  "Omnichannel Retail",
  "Online Shopping",
  "Mobile Commerce",
  "B2B E-commerce",
  "Retail Technology",
  "Retail Analytics",
  "Dropshipping",
  "Fashion E-commerce",
  "Online Grocery",
  "Health and Beauty E-commerce",
  "E-commerce Logistics",
  "Product Customization",
  "Shopping Cart Solutions",
  "Cross-Border E-commerce",
  "E-commerce Payment Solutions",
  "Digital Retail",
  "Online Marketplaces",
  "Supply Chain for Retail",

  // **Technology & Software**
  "Software Development",
  "Information Technology",
  "Technology",
  "Cloud Computing",
  "Artificial Intelligence",
  "Cybersecurity",
  "Machine Learning",
  "Blockchain",
  "Mobile App Development",
  "SaaS (Software as a Service)",
  "IT Services and IT Consulting",
  "Semiconductor Manufacturing",
  "Internet of Things (IoT)",
  "Tech Startups",
  "Data Science",
  "Data Analytics",
  "Enterprise Software",
  "Virtual Reality",
  "Augmented Reality",
  "Tech Support",
  "E-commerce Technology",
  "Web Development",
  "DevOps",
  "FinTech Technology",
  "Tech Infrastructure",
  "Quantum Computing",
  "Edge Computing",
  "App Development",
  "Cloud Services",
  "Tech Solutions",
  "Cloud Infrastructure",
  "Data Engineering",
  "Software as a Service (SaaS)",
  "Platform-as-a-Service (PaaS)",
  "Cyber-Physical Systems",
  "Tech Innovation",
  "Augmented Reality (AR)",
  "Deep Learning",
  "Big Data",
  "Edge AI",
  "Voice Assistants",
  "Robotic Process Automation (RPA)",
  "Digital Transformation",
  "Low-Code Platforms",
  "No-Code Platforms",
  "Artificial General Intelligence (AGI)",
  "Digital Twins",

  // **Finance & Insurance**
  "Financial Services",
  "Banking",
  "Insurance",
  "Investment Banking",
  "Financial Planning",
  "Asset Management",
  "FinTech",
  "Cryptocurrency",
  "Wealth Management",
  "Accounting",
  "Private Equity",
  "Venture Capital",
  "Hedge Funds",
  "Compliance",
  "Risk Management",
  "Payment Processing",
  "Mortgage Banking",
  "Financial Analysis",
  "Retirement Planning",
  "Actuarial Services",
  "Underwriting",
  "Financial Compliance",
  "Risk Assessment",
  "Personal Finance",
  "Peer-to-Peer Lending",
  "Crowdfunding",
  "Digital Banking",
  "Cryptocurrency Trading",
  "InsurTech",
  "WealthTech",
  "Blockchain Finance",
  "Risk Analytics",
  "Microfinance",
  "Alternative Investments",
  "Insurance Claims",
  "RegTech (Regulatory Technology)",
  "Blockchain-based Finance",
  "Financial Forecasting",
  "AI in Finance",
  "Financial Data Analysis",
  "Digital Wallets",
  "Payment Gateways",
  "Crowdsourced Investments",

  // **Healthcare & Life Sciences**
  "Healthcare",
  "Medical Devices",
  "Biotechnology",
  "Pharmaceuticals",
  "Healthcare IT",
  "Clinical Research",
  "Mental Health",
  "Public Health",
  "Telemedicine",
  "Hospitals & Healthcare Systems",
  "Health and Wellness",
  "Physical Therapy",
  "Medical Research",
  "Nursing",
  "Doctor/Physician",
  "Dental Care",
  "Veterinary",
  "Nutrition and Dietetics",
  "Alternative Medicine",
  "Genomics",
  "Medical Diagnostics",
  "Home Health Care",
  "Health Insurance",
  "Medical Billing and Coding",
  "Pediatrics",
  "Geriatrics",
  "Healthcare Administration",
  "Pharmaceutical Marketing",
  "Health Tech",
  "Medical AI",
  "Biopharmaceuticals",
  "Healthcare Data",
  "Genetic Testing",
  "Clinical Trials",
  "Health Insurance Portability",
  "Remote Healthcare",
  "Telehealth Platforms",
  "Nutraceuticals",
  "Mental Health Apps",
  "Medical Supply Chain",
  "Clinical Trials Management",
  "Medical Research Funding",
  "Healthcare Analytics",
  "Personalized Medicine",
  "Health Data Interoperability",
  "Healthcare Robotics",
  "Telehealth Solutions",

  // **Manufacturing & Engineering**
  "Manufacturing",
  "Industrial Automation",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Civil Engineering",
  "Construction",
  "Automotive Manufacturing",
  "Aerospace Engineering",
  "Robotics",
  "Textile Manufacturing",
  "Chemicals",
  "Plastics",
  "Heavy Machinery",
  "Electronics Manufacturing",
  "Food Manufacturing",
  "Precision Engineering",
  "Mining and Metals",
  "Logistics and Distribution",
  "Supply Chain Management",
  "Energy Production",
  "Construction Equipment",
  "3D Printing",
  "Industrial Design",
  "Fabrication",
  "Heavy Equipment",
  "Structural Engineering",
  "Environmental Engineering",
  "Renewable Energy Engineering",
  "Automation Solutions",
  "Industrial Robotics",
  "Smart Manufacturing",
  "Additive Manufacturing",
  "Precision Manufacturing",
  "CNC Machining",
  "Construction Technology",
  "Green Manufacturing",
  "Product Design and Development",
  "Advanced Materials",
  "Heavy Industrial Equipment",
  "Industrial Supply Chain",
  "Material Handling",
  "Smart Factories",
  "Facility Management",
  "Smart Logistics",
  "Supply Chain Analytics",
  "Sustainable Manufacturing",
  "Industrial IoT",

  // **Education**
  "Education",
  "K-12 Education",
  "Higher Education",
  "EdTech",
  "Online Education",
  "Curriculum Development",
  "Tutoring",
  "Educational Consulting",
  "Teaching",
  "Academic Research",
  "Special Education",
  "Language Teaching",
  "STEM Education",
  "Test Preparation",
  "Vocational Training",
  "Adult Education",
  "Learning and Development",
  "Corporate Training",
  "E-Learning",
  "Instructional Design",
  "Language Schools",
  "Education Technology",
  "Study Abroad",
  "Academic Publishing",
  "Public Speaking",
  "After-School Programs",
  "EdTech Innovation",
  "Learning Management Systems (LMS)",
  "Online Courses",
  "Distance Learning",
  "Adaptive Learning",
  "Corporate E-Learning",
  "Higher Education Institutions",
  "Academic Advising",
  "K-12 Online Learning",
  "University Research",
  "Homeschooling Resources",
  "Education Policy",
  "Digital Classrooms",
  "Learning Analytics",
  "Teacher Training",
  "Education Consulting",
  "Curriculum Design",
  "Blended Learning",

  // **Real Estate**
  "Real Estate",
  "Commercial Real Estate",
  "Residential Real Estate",
  "Real Estate Investment",
  "Property Management",
  "Real Estate Development",
  "Real Estate Sales",
  "Leasing",
  "Mortgage Brokers",
  "Real Estate Finance",
  "Real Estate Marketing",
  "Construction",
  "Land Development",
  "Property Law",
  "Real Estate Brokerage",
  "Real Estate Agents",
  "Property Investment",
  "Real Estate Appraisal",
  "Real Estate Technology",
  "Real Estate Investment Trusts (REITs)",
  "Real Estate Crowdfunding",
  "Property Tech",
  "Smart Homes",
  "Real Estate Development Software",
  "Property Management Software",
  "Real Estate Marketing Automation",
  "Commercial Leasing",
  "Real Estate Syndication",
  "Short-Term Rentals",
  "Luxury Real Estate",
  "Real Estate Photography",
  "Real Estate Auctions",
  "Urban Development",
  "Smart Cities",
  "Real Estate Market Analysis",
  "Sustainable Real Estate",
  "Real Estate Investment Platforms",

  // **Marketing & Advertising**
  "Marketing",
  "Digital Marketing",
  "SEO (Search Engine Optimization)",
  "PPC (Pay-Per-Click)",
  "Social Media Marketing",
  "Content Marketing",
  "Branding",
  "Public Relations",
  "Email Marketing",
  "Affiliate Marketing",
  "Market Research",
  "Event Marketing",
  "Influencer Marketing",
  "Video Marketing",
  "Marketing Automation",
  "Advertising",
  "Ad Tech",
  "Creative Services",
  "Traditional Advertising",
  "Outdoor Advertising",
  "Influencer Relations",
  "Brand Strategy",
  "Creative Direction",
  "Retail Marketing",
  "E-commerce Marketing",
  "Search Engine Marketing (SEM)",
  "Programmatic Advertising",
  "Content Creation",
  "Performance Marketing",
  "Creative Campaigns",
  "Brand Awareness",
  "Lead Generation",
  "B2B Marketing",
  "B2C Marketing",
  "Brand Engagement",
  "Customer Retention",
  "Product Launch Marketing",
  "Digital Advertising Platforms",
  "Cross-channel Marketing",
  "Data-driven Marketing",

  // **Media & Entertainment**
  "Media",
  "Broadcasting",
  "Journalism",
  "Film Production",
  "Music Production",
  "Television Production",
  "Content Creation",
  "Video Production",
  "Podcasting",
  "Photography",
  "Advertising Media",
  "Public Relations",
  "Event Planning",
  "Social Media Management",
  "Publishing",
  "Sports and Entertainment",
  "Film Distribution",
  "Theater Arts",
  "Animation",
  "Game Design",
  "Content Management",
  "Film Editing",
  "Music Distribution",
  "Digital Media",
  "Entertainment Technology",
  "Video Streaming",
  "Virtual Events",
  "Film Marketing",
  "Music Licensing",
  "Podcasting Production",
  "Digital Publishing",
  "Media Strategy",
  "Film Festivals",
  "Live Streaming",
  "Influencer Content",
  "Broadcast Networks",
  "Streaming Platforms",

  // **Hospitality & Tourism**
  "Hospitality",
  "Travel and Tourism",
  "Hotel Management",
  "Restaurants",
  "Food and Beverage",
  "Event Planning",
  "Leisure Travel",
  "Destination Management",
  "Tourism and Leisure",
  "Culinary Arts",
  "Resorts",
  "Concierge Services",
  "Cruise Lines",
  "Hotel Services",
  "Spa and Wellness",
  "Aviation",
  "Travel Agencies",
  "Car Rentals",
  "Tour Operators",
  "Hotel Real Estate",
  "Luxury Travel",
  "Adventure Travel",
  "Sustainable Tourism",
  "Tourism Marketing",
  "Hospitality Technology",
  "Travel Technology",
  "Event Catering",
  "Luxury Hotels",
  "Cultural Tourism",
  "Eco-Friendly Travel",
  "Destination Marketing",
  "Cruise Tourism",
  "Travel Experience",

  // **Legal**
  "Legal",
  "Corporate Law",
  "Criminal Law",
  "Civil Law",
  "Intellectual Property",
  "Family Law",
  "Contract Law",
  "Real Estate Law",
  "Tax Law",
  "Employment Law",
  "Immigration Law",
  "Bankruptcy Law",
  "Litigation",
  "Compliance",
  "Legal Research",
  "Paralegal Services",
  "Trial Law",
  "Legal Consulting",
  "Environmental Law",
  "Estate Planning",
  "Corporate Governance",
  "Patent Law",
  "Legal Tech",
  "Legal Process Outsourcing",
  "Alternative Dispute Resolution",
  "Mergers and Acquisitions Law",
  "Legal AI",
  "Legal Automation",
  "Regulatory Compliance",
  "Arbitration",

  // **Energy & Utilities**
  "Energy",
  "Oil and Gas",
  "Renewable Energy",
  "Utilities",
  "Clean Energy",
  "Environmental Services",
  "Mining",
  "Electric Power",
  "Energy Consulting",
  "Energy Storage",
  "Nuclear Energy",
  "Hydropower",
  "Geothermal Energy",
  "Energy Production",
  "Power Generation",
  "Solar Energy",
  "Wind Energy",
  "Energy Efficiency",
  "Electric Vehicles",
  "Battery Technology",
  "Smart Grids",
  "Energy Trading",
  "Energy Management",
  "Carbon Footprint Reduction",
  "Green Energy",
  "Energy Transition",

  // **Transportation & Logistics**
  "Transportation",
  "Logistics",
  "Supply Chain",
  "Shipping",
  "Freight",
  "Warehousing",
  "Fleet Management",
  "Airlines",
  "Railroads",
  "Automotive",
  "Public Transit",
  "Maritime",
  "Trucking",
  "Delivery Services",
  "Cargo Shipping",
  "Transportation Consulting",
  "Logistics Software",
  "Last Mile Delivery",
  "Cold Chain Logistics",
  "Supply Chain Optimization",
  "Logistics Automation",
  "Fleet Tracking",
  "Global Logistics",
  "Cargo Management",

  // **Telecommunications**
  "Telecommunications",
  "Mobile Networks",
  "Wireless Communications",
  "Broadband",
  "5G Technology",
  "Satellite Communications",
  "Internet Service Providers",
  "Telecom Infrastructure",
  "VoIP",
  "Telecom Equipment",
  "Fiber Optics",
  "Unified Communications",
  "Telecom Sales",
  "Telecom IT",
  "Telecom Software",

  // **Non-Profit & Social Impact**
  "Non-profit",
  "Charity",
  "Philanthropy",
  "Social Impact",
  "Community Outreach",
  "Fundraising",
  "NGOs (Non-Governmental Organizations)",
  "Social Services",
  "International Aid",
  "Environmental Advocacy",
  "Human Rights",
  "Disaster Relief",
  "Sustainability",
  "Social Entrepreneurship",
  "Volunteer Services",
  "Social Welfare",

  // **Staffing & Recruiting**
  "Staffing and Recruiting",
  "Human Resources",
  "Recruitment",
  "Talent Acquisition",
  "Workforce Solutions",
  "Executive Search",
  "Employee Benefits",
  "Labor Relations",
  "Payroll Services",
  "Recruitment Process Outsourcing (RPO)",
  "Workforce Management",
  "Talent Development",
  "Employee Engagement",

  // **Consumer Services**
  "Customer Service",
  "Retail Support",
  "Home Services",
  "Personal Assistance",
  "Cleaning Services",
  "Real Estate Services",
  "Automotive Services",
  "Entertainment Services",
  "Maintenance Services",

  // **Consulting & Professional Services**
  "Consulting",
  "Management Consulting",
  "Business Consulting",
  "Strategy Consulting",
  "Legal Consulting",
  "Financial Consulting",
  "IT Consulting",
  "HR Consulting",
  "Marketing Consulting",
  "Engineering Consulting",
  "Environmental Consulting",
  "Risk Management Consulting",
  "Operations Consulting",
  "Project Management",
  "Change Management",

  // **Web3 & NFTs**
  "Web3",
  "NFTs (Non-Fungible Tokens)",
  "Blockchain Technology",
  "Decentralized Finance (DeFi)",
  "Smart Contracts",
  "Cryptocurrency",
  "Cryptocurrency Trading",
  "Digital Assets",
  "NFT Art",
  "Tokenization",
  "Decentralized Apps (dApps)",
  "Ethereum",
  "Solana",
  "Binance Smart Chain",
  "Web3 Startups",
  "Metaverse",
  "DAO (Decentralized Autonomous Organization)",
  "NFT Marketplace",
  "Digital Collectibles",
  "Blockchain Gaming",
  "Play-to-Earn (P2E)",
  "Cryptographic Tokens",
  "Tokenomics",
  "Blockchain Identity",
  "Decentralized Web",
  "Web3 Infrastructure",
  "NFT Minting",
  "NFT Community",
  "Blockchain for Gaming",
  "Crypto Wallets",
  "Web3 Marketing",
  "NFT Drops",
  "Decentralized Exchange (DEX)",
  "NFTs for Enterprises",
  "Blockchain Solutions",
  "NFT Investment",
  "Web3 Finance",
  "Metaverse Real Estate",
  "NFT Art Creation",
  "Web3 Security",
];
