export const jobRoles = [
  {
    category: "Engineering",
    roles: [
      "Software Engineer",
      "Frontend Engineer",
      "Backend Engineer",
      "Full Stack Engineer",
      "DevOps Engineer",
      "Data Engineer",
      "Machine Learning Engineer",
      "QA Engineer",
      "Security Engineer",
      "Cloud Engineer",
      "Mobile Developer",
      "Embedded Systems Engineer",
      "Network Engineer",
      "Site Reliability Engineer",
      "Database Administrator (DBA)",
      "Systems Architect",
      "AI Engineer",
      "Blockchain Engineer",
      "Cloud Solutions Architect",
      "Release Manager",
      "Automation Engineer",
      "Firmware Engineer",
      "Game Developer",
      "Product Engineer",
      "Web Developer",
      "Systems Engineer",
      "Technical Lead",
      "Cloud Solutions Engineer",
      "Database Engineer",
      "Application Support Engineer",
      "Infrastructure Engineer",
      "Data Scientist",
      "AI/ML Researcher",
      "Automation Test Engineer",
      "Test Architect",
      "IoT Engineer",
      "Performance Engineer",
      "Integration Engineer",
      "Cybersecurity Analyst",
      "Blockchain Developer",
      "Data Analyst",
      "Business Intelligence Analyst",
      "Cloud Architect",
      "Data Architect",
      "Data Operations Engineer",
    ],
  },
  {
    category: "Data & Business Intelligence",
    roles: [
      "Data Analyst",
      "Business Intelligence Analyst",
      "Data Scientist",
      "Business Analyst",
      "Data Engineer",
      "Data Architect",
      "Business Intelligence Developer",
      "Data Visualization Specialist",
      "Quantitative Analyst",
      "Operations Analyst",
      "Data Operations Engineer",
      "Market Research Analyst",
      "Big Data Engineer",
      "Machine Learning Engineer",
      "AI Researcher",
      "Data Analyst Intern",
      "Data Quality Analyst",
      "Data Governance Specialist",
      "Analytics Manager",
      "Product Analyst",
    ],
  },
  {
    category: "Design",
    roles: [
      "UX Designer",
      "UI Designer",
      "Product Designer",
      "Graphic Designer",
      "Visual Designer",
      "Interaction Designer",
      "Industrial Designer",
      "Motion Designer",
      "Design Lead",
      "Art Director",
      "Brand Designer",
      "Web Designer",
      "Illustrator",
      "Typographer",
      "UI/UX Researcher",
      "Design Systems Lead",
      "3D Designer",
      "Experience Designer",
      "Creative Director",
      "Digital Designer",
      "Packaging Designer",
      "Concept Artist",
      "User Interface Developer",
      "Design Researcher",
      "User Experience Architect",
      "Visual Storyteller",
      "Creative Strategist",
      "UI Developer",
      "Design Technologist",
      "Environmental Designer",
      "Video Editor",
      "Product Illustrator",
      "Graphic Design Intern",
      "Digital Art Director",
      "Mobile App Designer",
      "Information Designer",
      "Brand Strategist",
      "Experience Design Lead",
      "User Interface Architect",
      "Web Design Specialist",
      "Content Designer",
      "User Interface Designer",
    ],
  },
  {
    category: "Operations",
    roles: [
      "Operations Manager",
      "Project Manager",
      "Supply Chain Manager",
      "Logistics Coordinator",
      "Business Operations Analyst",
      "Facilities Manager",
      "Customer Support Manager",
      "Vendor Manager",
      "Process Improvement Specialist",
      "Operations Coordinator",
      "Chief Operating Officer (COO)",
      "Business Analyst",
      "Operations Director",
      "Inventory Manager",
      "Fleet Manager",
      "Service Delivery Manager",
      "Warehouse Manager",
      "Quality Assurance Manager",
      "Scrum Master",
      "Risk Manager",
      "Compliance Officer",
      "Product Operations Specialist",
      "Continuous Improvement Manager",
      "Operations Research Analyst",

      "Chief Financial Officer (CFO)",
      "Financial Analyst",
      "Finance Manager",
      "Financial Planner & Analyst (FP&A)",
      "Accounting Manager",
      "Tax Manager",
      "Investment Analyst",
      "Controller",
      "Treasury Manager",
      "Credit Analyst",
      "Audit Manager",
      "Risk Analyst",
      "Accounting Clerk",
      "Bookkeeper",
      "Internal Auditor",
      "Financial Reporting Manager",
      "Forensic Accountant",
      "Payroll Manager",
      "Budget Analyst",
      "Accounts Payable Clerk",
      "Accounts Receivable Clerk",
      "Corporate Finance Analyst",
      "Mergers & Acquisitions Analyst",
      "Financial Systems Analyst",
      "Portfolio Manager",
      "Actuary",
      "Finance Director",
      "Credit Controller",
      "Financial Operations Manager",
      "Tax Associate",
      "Financial Data Analyst",
      "Accounts Payable Manager",
      "Corporate Accountant",

      "Accountant",
      "Senior Accountant",
      "Junior Accountant",
      "Accounting Assistant",
      "Cost Accountant",
      "Management Accountant",
      "Tax Accountant",
      "External Auditor",
      "Internal Auditor",
      "Payroll Accountant",
      "Accounts Payable Specialist",
      "Accounts Receivable Specialist",
      "Tax Advisor",
      "Bookkeeper",
      "Financial Accountant",
      "Accounting Manager",
      "Audit Associate",
      "Revenue Accountant",
      "Accounting Analyst",
      "Tax Specialist",
      "Business Accountant",
      "Audit Manager",
      "Fund Accountant",
      "Credit Analyst",

      "HR Manager",
      "HR Director",
      "HR Specialist",
      "Recruiter",
      "Talent Acquisition Manager",
      "HR Business Partner",
      "Compensation and Benefits Manager",
      "Employee Relations Specialist",
      "HR Coordinator",
      "HR Generalist",
      "Payroll Specialist",
      "Training and Development Manager",
      "Organizational Development Specialist",
      "Diversity and Inclusion Manager",
      "Recruitment Coordinator",
      "Onboarding Specialist",
      "HR Assistant",
      "HR Analyst",
      "HR Consultant",
      "Chief People Officer (CPO)",
      "Labor Relations Specialist",
      "HR Operations Manager",
      "People Operations Manager",
      "Workplace Wellness Manager",
      "Learning and Development Specialist",
      "People Analytics Specialist",
      "HRIS Analyst",
      "Employee Engagement Specialist",
      "Compensation Analyst",
      "Talent Management Specialist",
      "HR Operations Coordinator",
      "Executive Recruiter",
      "Workforce Planning Specialist",
    ],
  },
  {
    category: "Sales",
    roles: [
      "Sales Manager",
      "Account Executive",
      "Sales Development Representative",
      "Business Development Manager",
      "Sales Operations Analyst",
      "Regional Sales Director",
      "Inside Sales Representative",
      "Enterprise Account Manager",
      "Channel Sales Manager",
      "Sales Engineer",
      "Sales Enablement Manager",
      "Account Manager",
      "Territory Sales Manager",
      "Global Sales Director",
      "Key Account Manager",
      "Customer Success Manager",
      "Sales Consultant",
      "Lead Generation Specialist",
      "Sales Strategist",
      "Director of Sales",
      "Sales Trainer",
      "Client Relationship Manager",
      "Sales Analyst",
      "Field Sales Representative",
      "Sales Executive",
      "Regional Sales Manager",
      "Sales Coordinator",
      "Inside Sales Manager",
      "VP of Sales",
      "Sales Operations Manager",
      "National Sales Manager",
      "Sales Director",
      "Channel Account Manager",
      "Strategic Account Manager",
      "Client Success Manager",
      "Sales Operations Manager",
      "Sales Development Leader",
    ],
  },
  {
    category: "Marketing",
    roles: [
      "Marketing Manager",
      "Content Strategist",
      "SEO Specialist",
      "Digital Marketing Manager",
      "Social Media Manager",
      "Growth Hacker",
      "Product Marketing Manager",
      "Brand Manager",
      "Marketing Analyst",
      "Public Relations Specialist",
      "Event Coordinator",
      "Email Marketing Specialist",
      "PPC Specialist",
      "Influencer Marketing Manager",
      "Marketing Director",
      "Campaign Manager",
      "Creative Copywriter",
      "Community Manager",
      "Marketing Operations Manager",
      "E-commerce Manager",
      "Market Research Analyst",
      "Copywriter",
      "Video Content Creator",
      "Marketing Automation Specialist",
      "Affiliate Marketing Manager",
      "Brand Strategist",
      "Customer Insights Manager",
      "User Acquisition Specialist",
      "Marketing Data Analyst",
      "Social Media Strategist",
      "Marketing Coordinator",
      "Content Marketing Manager",
      "Brand Strategist",
      "Marketing Communications Manager",
      "Performance Marketing Manager",
      "Product Copywriter",
      "Conversion Rate Optimization Specialist",
      "Demand Generation Manager",
      "Growth Marketing Manager",
      "Marketing Campaign Analyst",
      "CRM Marketing Manager",
      "Digital Advertising Specialist",
      "Event Marketing Manager",
      "Public Relations Manager",
      "SEO/SEM Manager",
      "Marketing Data Analyst",
      "Brand Strategist",
      "Affiliate Marketing Manager",
    ],
  },
];
