export const skillKeywords = [
  // ------------------------------- FRONTEND TECHNOLOGIES -------------------------------

  // Core Frontend
  "HTML",
  "HTML5",
  "CSS",
  "CSS3",
  "Tailwind CSS",
  "Tailwind",
  "SASS",
  "LESS",
  "Styled Components",
  "CSS preprocessors",
  "Bootstrap",
  "Semantic UI",
  "Material-UI",
  "MUI",
  "Chakra UI",
  "Flexbox",
  "Grid Layout",
  "BEM",
  "Atomic CSS",
  "PostCSS",
  "CSS-in-JS",
  "CSS Grid",

  // JavaScript & Libraries
  "JavaScript",
  "ES6",
  "TypeScript",
  "React",
  "React.js",
  "React Native",
  "Vue.js",
  "Vue",
  "Angular",
  "Redux",
  "Preact",
  "SvelteJS",
  "Next.js",
  "Next",
  "Nuxt.js",
  "Nuxt",
  "Express.js",
  "Node.js",
  "jQuery",
  "Vanilla JS",
  "Vanilla JavaScript",
  "Redux Toolkit",
  "React Query",
  "Tanstack Query",
  "React Spring",
  "Framer Motion",
  "React Testing Library",
  "RxJS",
  "WebSockets",
  "WebRTC",
  "Socket.io",
  "GraphQL",
  "GraphQL Queries",
  "GraphQL Mutations",
  "GraphQL Subscriptions",
  "Apollo",
  "tRPC",
  "XState",
  "MobX",
  "Jotai",
  "Zustand",
  "GraphQL Relay",
  "Babel",
  "ESLint",
  "Prettier",
  "Webpack",
  "Vite",
  "Rollup",
  "Parcel",
  "Storybook",
  "TurboRepo", // Build tool for monorepos
  "NextAuth.js", // Authentication for Next.js

  // Testing & Tools
  "Jest",
  "Cypress",
  "Mocha",
  "Puppeteer",
  "Chai",
  "Jasmine",
  "Karma",
  "Enzyme",
  "Selenium",
  "Playwright",
  "Vitest",
  "WebDriverIO",
  "Test Driven Development",
  "Unit Testing",
  "Integration Testing",
  "API Testing",
  "Automated Testing",
  "TestNG",
  "JUnit",

  // Mobile Development
  "React Native",
  "Flutter",
  "iOS",
  "Android",
  "Expo",
  "Swift",
  "Kotlin",
  "Objective-C",
  "Xcode",
  "Android Studio",
  "Dart",
  "Ionic",
  "Cordova",
  "PhoneGap",
  "WebView",
  "Mobile Web App",
  "Progressive Web App (PWA)",
  "Hybrid Apps",
  "Capacitor",
  "Flutter Web",
  "NativeScript",
  "Xamarin", // Mobile app development for iOS and Android

  // Design & UX Tools
  "Figma",
  "Sketch",
  "Adobe XD",
  "Zeplin",
  "Canva",
  "Adobe Illustrator",
  "Adobe Photoshop",
  "InVision",
  "Balsamiq",
  "Axure",
  "Storybook",
  "UI Design",
  "UX Design",
  "User Testing",
  "Wireframing",
  "Prototyping",
  "Interaction Design",
  "User Flow",
  "UI/UX",
  "User-Centered Design",

  // 3D Graphics & Game Development
  "Three.js",
  "WebGL",
  "Babylon.js",
  "Unity3D",
  "Unreal Engine",
  "Blender",
  "Mapbox",
  "WebVR",
  "Game Development",
  "GLTF",
  "Game Engine",
  "A-Frame",
  "Vuforia",
  "AR/VR Development",

  // ------------------------------- BACKEND TECHNOLOGIES -------------------------------

  // Backend Languages & Frameworks
  "Node.js",
  "Express.js",
  "Java",
  "Spring Boot",
  "Spring",
  "Python",
  "Flask",
  "Django",
  "Ruby",
  "Ruby on Rails",
  "PHP",
  "Go (Golang)",
  "Golang",
  "C#",
  "Elixir",
  "Phoenix",
  "Rust",
  "C++",
  "Scala",
  "Kotlin",
  "FastAPI",
  "Nest.js",
  "Nest",
  "Laravel",
  ".NET",
  "ASP.NET",
  "Symfony",
  "Perl",
  "Clojure",
  "Haskell",
  "Erlang",
  "Objective-C",
  "Swift",
  "Solidity",
  "Smart Contracts",
  "Vapor",
  "Gin (Golang framework)",
  "Quarkus",
  "F#",

  // Databases & Data Storage
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Mongoose",
  "SQLite",
  "MariaDB",
  "Redis",
  "Cassandra",
  "ScyllaDB",
  "ElasticSearch",
  "Bigtable",
  "CouchDB",
  "Neo4j",
  "DynamoDB",
  "Firebase",
  "Firebase Realtime Database",
  "Firebase Cloud Firestore",
  "Supabase",
  "Amazon RDS",
  "Microsoft SQL Server",
  "BigQuery",
  "Google Cloud SQL",
  "Google Datastore",
  "Amazon S3",
  "Amazon Redshift",
  "MemcacheD",
  "Graph Database",
  "GraphQL",
  "API Gateway",
  "GraphQL API",
  "Data Lake",
  "Data Warehousing",
  "OLAP",
  "OLTP",
  "Columnar Databases",
  "AWS Lambda",
  "Google Bigtable",
  "Amazon DynamoDB",

  // DevOps & Cloud Platforms
  "Docker",
  "Kubernetes",
  "CI / CD",
  "CircleCI",
  "GitHub Actions",
  "GitLab CI",
  "Jenkins",
  "Travis CI",
  "AWS",
  "Google Cloud",
  "Azure",
  "GCP",
  "Google Cloud Platform",
  "AWS Lambda",
  "Elastic Beanstalk",
  "CloudFormation",
  "Terraform",
  "Pulumi",
  "Kubernetes (K8s)",
  "Helm",
  "AWS ECS",
  "AWS EKS",
  "Serverless",
  "Fargate",
  "Vercel",
  "Netlify",
  "Heroku",
  "DigitalOcean",
  "Cloudflare",
  "Terraform",
  "Packer",
  "Ansible",
  "Jenkins",
  "Bamboo",
  "OpenShift",
  "Amazon EC2",
  "Amazon S3",
  "Amazon CloudFront",
  "AWS Fargate",
  "Google Kubernetes Engine (GKE)",

  // APIs & Microservices
  "REST API",
  "RESTful APIs",
  "GraphQL API",
  "gRPC",
  "WebSockets",
  "API Documentation",
  "Swagger",
  "OpenAPI",
  "OAuth",
  "JWT Tokens",
  "API Gateway",
  "Rate Limiting",
  "API Testing",
  "Webhooks",
  "Microservices",
  "Serverless Architecture",
  "Containerization",
  "Message Queues",
  "RabbitMQ",
  "Kafka",
  "NATS",
  "Azure Functions",
  "Azure Logic Apps",
  "AWS Step Functions",
  "Cloud Functions",
  "Apache Pulsar",

  // Authentication & Security
  "OAuth",
  "JWT",
  "JWT Tokens",
  "Auth0",
  "Passport.js",
  "Clerk",
  "Firebase Auth",
  "Single Sign-On (SSO)",
  "Multi-Factor Authentication (MFA)",
  "Identity Management",
  "Session Management",
  "Role-Based Access Control (RBAC)",
  "XSS",
  "SQL Injection",
  "Security Audits",
  "Web Application Firewall (WAF)",
  "CORS",
  "Helmet.js",
  "OWASP",
  "Penetration Testing",
  "Encryption",
  "PKI",
  "TLS",
  "SSL",
  "Data Privacy",
  "Zero Trust Security",

  // Testing & Quality Assurance
  "Jest",
  "Mocha",
  "Chai",
  "Jasmine",
  "Cypress",
  "Puppeteer",
  "Selenium",
  "Playwright",
  "Vitest",
  "JUnit",
  "TestNG",
  "Unit Testing",
  "Integration Testing",
  "End-to-End Testing",
  "Mocking",
  "Test Coverage",
  "API Testing",
  "Load Testing",
  "Performance Testing",
  "Static Analysis",
  "Test Driven Development (TDD)",
  "Continuous Integration",
  "Code Coverage",
  "Test Automation",
  "Selenium WebDriver",
  "Cucumber",
  "BDD",
  "Testrail",
  "Bug Tracking",

  // ------------------------------- MARKETING TECHNOLOGIES -------------------------------

  // Analytics & Marketing Automation
  "Google Analytics",
  "Google Tag Manager",
  "Mixpanel",
  "Amplitude",
  "Kissmetrics",
  "Matomo",
  "Adobe Analytics",
  "HubSpot",
  "Marketo",
  "Mailchimp",
  "SendGrid",
  "Zapier",
  "IFTTT",
  "A/B Testing",
  "Optimizely",
  "Unbounce",
  "Klaviyo",
  "ConvertKit",
  "Mailchimp",
  "Google Optimize",
  "VWO",
  "SurveyMonkey",
  "Litmus",
  "Caniemail",
  "Segment",
  "Pardot",
  "ActiveCampaign",
  "Moosend",
  "ClickFunnels",
  "Drip",
  "Customer.io",
  "Omnisend",

  // Social Media & Content Marketing
  "SEO",
  "On-Page SEO",
  "Off-Page SEO",
  "Technical SEO",
  "Keyword Research",
  "Link Building",
  "Content Marketing",
  "Social Media Marketing",
  "Facebook Ads",
  "Instagram Ads",
  "LinkedIn Ads",
  "Google Ads",
  "Twitter Ads",
  "TikTok Ads",
  "Pinterest Ads",
  "Influencer Marketing",
  "Content Strategy",
  "Content Creation",
  "Blogging",
  "Video Marketing",
  "Lead Generation",
  "Lead Nurturing",
  "PPC",
  "CPC",
  "CPA",
  "CPM",
  "Affiliate Marketing",
  "Referral Programs",
  "Influencer Outreach",
  "Campaign Management",
  "Social Media Strategy",
  "Social Media Analytics",
  "TikTok Marketing",
  "YouTube Marketing",

  // CRM & Customer Relations
  "CRM",
  "HubSpot CRM",
  "Salesforce",
  "Zoho CRM",
  "Intercom",
  "Zendesk",
  "Freshdesk",
  "PandaDoc",
  "Asana",
  "Trello",
  "Slack",
  "Zendesk",
  "Lead Scoring",
  "Customer Journeys",
  "Customer Retention",
  "Sales Funnels",
  "Email Campaigns",
  "Email Marketing",
  "SMS Marketing",
  "Customer Segmentation",
  "Marketing Automation",
  "Retargeting",
  "Churn Rate",

  // Content Management & eCommerce
  "WordPress",
  "Shopify",
  "WooCommerce",
  "Magento",
  "BigCommerce",
  "Squarespace",
  "Webflow",
  "Odoo",
  "Headless CMS",
  "Contentful",
  "Prismic",
  "Strapi",
  "Salesforce Commerce Cloud",
  "Shopify Plus",
  "Shopify API",
  "WooCommerce API",
  "Contentful CMS",
  "BigCommerce API",
  "WebShop",
  "eCommerce",
  "Payment Gateways",
  "Stripe",
  "PayPal",
  "Square",
  "Braintree",
  "Coinbase Commerce",
  "Amazon Payments",
  "WooCommerce Subscriptions",
  "Shopify Payments",

  // Business Intelligence & Data Visualization
  "Tableau",
  "PowerBI",
  "Looker",
  "Mode Analytics",
  "D3.js",
  "Plotly",
  "Chart.js",
  "Highcharts",
  "Data Analysis",
  "Data Visualization",
  "Google Data Studio",
  "Excel",
  "Google Sheets",
  "Microsoft PowerPoint",
  "Business Intelligence (BI)",
  "Google BigQuery",
  "SQL Reporting",
  "KPI Dashboards",
  "ETL Tools",

  // ------------------------------- EMERGING TECHNOLOGIES -------------------------------

  // Artificial Intelligence & Machine Learning
  "AI",
  "Artificial Intelligence",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing (NLP)",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "ML Ops",
  "SciPy",
  "NumPy",
  "OpenAI",
  "GPT-3",
  "Stable Diffusion",
  "DALL-E",
  "BERT",
  "XLNet",
  "XGBoost",
  "Random Forest",
  "Reinforcement Learning",
  "Neural Networks",
  "AI Models",
  "AI Algorithms",
  "Artificial Neural Networks",
  "Computer Vision",
  "Convolutional Neural Networks (CNNs)",

  // Blockchain & Web3
  "Blockchain",
  "Ethereum",
  "Solidity",
  "Web3",
  "Smart Contracts",
  "Decentralized Finance (DeFi)",
  "dApp",
  "IPFS",
  "NFTs",
  "Solana",
  "Polkadot",
  "Cryptocurrency",
  "Metamask",
  "Truffle",
  "Infura",
  "Metaplex",
  "Web3.js",
  "Web3 Development",
  "Ethers.js",
  "Decentralized Identity",
  "DAO",
  "Ethereum 2.0",
  "Layer 2 Solutions",
  "ZK-Rollups",
  "Chainlink",
  "Oracles",
  "NFT Marketplaces",
  "Bitcoin",
  "Solana",
  "Polkadot",

  // Data Engineering
  "ETL",
  "Data Pipelines",
  "Apache Kafka",
  "Apache Spark",
  "Airflow",
  "Flink",
  "Hadoop",
  "HDFS",
  "Pig",
  "Hive",
  "Apache Storm",
  "Kinesis",
  "Databricks",
  "Big Data",
  "Data Lakes",
  "Data Warehousing",
  "OLAP",
  "OLTP",
  "ClickHouse",
  "Iceberg",

  // Microservices & Serverless
  "Microservices",
  "Serverless Architecture",
  "AWS Lambda",
  "Azure Functions",
  "Google Cloud Functions",
  "Event-Driven Architecture",
  "RabbitMQ",
  "Kafka",
  "NATS",
  "Cloud Event",
  "API Gateway",
  "Message Queues",
  "CQRS",
  "Event Sourcing",
];
