export interface SkillDefinition {
  name: string;
}

export const skillKeywords: Record<string, SkillDefinition> = {
  Chai: { name: "Chai" },
  Java: { name: "Java" },
  Ember: { name: "Ember" },
  Expo: { name: "Expo" },
  DeFi: { name: "Decentralized Finance (DeFi)" },
  Scala: { name: "Scala" },
  HTML: { name: "HTML" },
  HTML5: { name: "HTML5" },
  CSS: { name: "CSS" },
  CSS3: { name: "CSS3" },
  TailwindCSS: { name: "Tailwind CSS" },
  SASS: { name: "SASS" },
  LESS: { name: "LESS" },
  StyledComponents: { name: "Styled Components" },
  CSSPreprocessors: { name: "CSS preprocessors" },
  Bootstrap: { name: "Bootstrap" },
  SemanticUI: { name: "Semantic UI" },
  MaterialUI: { name: "Material-UI" },
  ChakraUI: { name: "Chakra UI" },
  Flexbox: { name: "Flexbox" },
  GridLayout: { name: "Grid Layout" },
  BEM: { name: "BEM" },
  AtomicCSS: { name: "Atomic CSS" },
  PostCSS: { name: "PostCSS" },
  CSSinJS: { name: "CSS-in-JS" },
  CSSGrid: { name: "CSS Grid" },
  JavaScript: { name: "JavaScript" },
  ES6: { name: "ES6" },
  TypeScript: { name: "TypeScript" },
  React: { name: "React" },
  ReactNative: { name: "React Native" },
  VueJS: { name: "Vue.js" },
  Angular: { name: "Angular" },
  Redux: { name: "Redux" },
  Preact: { name: "Preact" },
  SvelteJS: { name: "SvelteJS" },
  NextJS: { name: "Next.js" },
  NuxtJS: { name: "Nuxt.js" },
  ExpressJS: { name: "Express.js" },
  NodeJS: { name: "Node.js" },
  jQuery: { name: "jQuery" },
  ReduxToolkit: { name: "Redux Toolkit" },
  ReactQuery: { name: "React Query" },
  ReactSpring: { name: "React Spring" },
  FramerMotion: { name: "Framer Motion" },
  ReactTestingLibrary: { name: "React Testing Library" },
  RxJS: { name: "RxJS" },
  WebSockets: { name: "WebSockets" },
  WebRTC: { name: "WebRTC" },
  SocketIO: { name: "Socket.io" },
  GraphQL: { name: "GraphQL" },
  GraphQLQueries: { name: "GraphQL Queries" },
  GraphQLMutations: { name: "GraphQL Mutations" },
  GraphQLSubscriptions: { name: "GraphQL Subscriptions" },
  Apollo: { name: "Apollo" },
  tRPC: { name: "tRPC" },
  XState: { name: "XState" },
  MobX: { name: "MobX" },
  Jotai: { name: "Jotai" },
  Zustand: { name: "Zustand" },
  GraphQLRelay: { name: "GraphQL Relay" },
  Babel: { name: "Babel" },
  ESLint: { name: "ESLint" },
  Prettier: { name: "Prettier" },
  Webpack: { name: "Webpack" },
  Vite: { name: "Vite" },
  Rollup: { name: "Rollup" },
  Parcel: { name: "Parcel" },
  Storybook: { name: "Storybook" },
  TurboRepo: { name: "TurboRepo" },
  NextAuthJS: { name: "NextAuth.js" },
  Jest: { name: "Jest" },
  Cypress: { name: "Cypress" },
  Mocha: { name: "Mocha" },
  Puppeteer: { name: "Puppeteer" },
  Jasmine: { name: "Jasmine" },
  Karma: { name: "Karma" },
  Enzyme: { name: "Enzyme" },
  Selenium: { name: "Selenium" },
  Playwright: { name: "Playwright" },
  Vitest: { name: "Vitest" },
  WebDriverIO: { name: "WebDriverIO" },
  TestDrivenDevelopment: { name: "Test Driven Development" },
  UnitTesting: { name: "Unit Testing" },
  IntegrationTesting: { name: "Integration Testing" },
  APITesting: { name: "API Testing" },
  AutomatedTesting: { name: "Automated Testing" },
  TestNG: { name: "TestNG" },
  JUnit: { name: "JUnit" },
  Flutter: { name: "Flutter" },
  iOS: { name: "iOS" },
  Android: { name: "Android" },
  Swift: { name: "Swift" },
  Kotlin: { name: "Kotlin" },
  ObjectiveC: { name: "Objective-C" },
  Xcode: { name: "Xcode" },
  AndroidStudio: { name: "Android Studio" },
  Dart: { name: "Dart" },
  Ionic: { name: "Ionic" },
  Cordova: { name: "Cordova" },
  PhoneGap: { name: "PhoneGap" },
  WebView: { name: "WebView" },
  MobileWebApp: { name: "Mobile Web App" },
  ProgressiveWebApp: { name: "Progressive Web App (PWA)" },
  HybridApps: { name: "Hybrid Apps" },
  Capacitor: { name: "Capacitor" },
  FlutterWeb: { name: "Flutter Web" },
  NativeScript: { name: "NativeScript" },
  Xamarin: { name: "Xamarin" },
  Figma: { name: "Figma" },
  Sketch: { name: "Sketch" },
  AdobeXD: { name: "Adobe XD" },
  Zeplin: { name: "Zeplin" },
  Canva: { name: "Canva" },
  AdobeIllustrator: { name: "Adobe Illustrator" },
  AdobePhotoshop: { name: "Adobe Photoshop" },
  InVision: { name: "InVision" },
  Balsamiq: { name: "Balsamiq" },
  Axure: { name: "Axure" },
  UIDesign: { name: "UI Design" },
  UXDesign: { name: "UX Design" },
  UserTesting: { name: "User Testing" },
  Wireframing: { name: "Wireframing" },
  Prototyping: { name: "Prototyping" },
  InteractionDesign: { name: "Interaction Design" },
  UserFlow: { name: "User Flow" },
  UIUX: { name: "UI/UX" },
  UserCenteredDesign: { name: "User-Centered Design" },
  ThreeJS: { name: "Three.js" },
  WebGL: { name: "WebGL" },
  BabylonJS: { name: "Babylon.js" },
  Unity3D: { name: "Unity3D" },
  UnrealEngine: { name: "Unreal Engine" },
  Blender: { name: "Blender" },
  Mapbox: { name: "Mapbox" },
  WebVR: { name: "WebVR" },
  GameDevelopment: { name: "Game Development" },
  GLTF: { name: "GLTF" },
  GameEngine: { name: "Game Engine" },
  AFrame: { name: "A-Frame" },
  Vuforia: { name: "Vuforia" },
  ARVRDevelopment: { name: "AR/VR Development" },
  Spring: { name: "Spring" },
  SpringBoot: { name: "Spring Boot" },
  Python: { name: "Python" },
  Flask: { name: "Flask" },
  Django: { name: "Django" },
  Ruby: { name: "Ruby" },
  RubyOnRails: { name: "Ruby on Rails" },
  PHP: { name: "PHP" },
  GoGolang: { name: "Go (Golang)" },
  CSharp: { name: "C#" },
  Elixir: { name: "Elixir" },
  Phoenix: { name: "Phoenix" },
  Rust: { name: "Rust" },
  CPlusPlus: { name: "C++" },
  FastAPI: { name: "FastAPI" },
  NestJS: { name: "Nest.js" },
  Laravel: { name: "Laravel" },
  DotNET: { name: ".NET" },
  ASPNET: { name: "ASP.NET" },
  Symfony: { name: "Symfony" },
  Perl: { name: "Perl" },
  Clojure: { name: "Clojure" },
  Haskell: { name: "Haskell" },
  Erlang: { name: "Erlang" },
  Solidity: { name: "Solidity" },
  SmartContracts: { name: "Smart Contracts" },
  Vapor: { name: "Vapor" },
  GinGolang: { name: "Gin (Golang framework)" },
  Quarkus: { name: "Quarkus" },
  FSharp: { name: "F#" },
  MySQL: { name: "MySQL" },
  PostgreSQL: { name: "PostgreSQL" },
  MongoDB: { name: "MongoDB" },
  Mongoose: { name: "Mongoose" },
  SQLite: { name: "SQLite" },
  MariaDB: { name: "MariaDB" },
  Redis: { name: "Redis" },
  Cassandra: { name: "Cassandra" },
  ScyllaDB: { name: "ScyllaDB" },
  ElasticSearch: { name: "ElasticSearch" },
  Bigtable: { name: "Bigtable" },
  CouchDB: { name: "CouchDB" },
  Neo4j: { name: "Neo4j" },
  DynamoDB: { name: "DynamoDB" },
  Firebase: { name: "Firebase" },
  FirebaseRealtimeDatabase: { name: "Firebase Realtime Database" },
  FirebaseCloudFirestore: { name: "Firebase Cloud Firestore" },
  Supabase: { name: "Supabase" },
  AmazonRDS: { name: "Amazon RDS" },
  MicrosoftSQLServer: { name: "Microsoft SQL Server" },
  BigQuery: { name: "BigQuery" },
  GoogleCloudSQL: { name: "Google Cloud SQL" },
  GoogleDatastore: { name: "Google Datastore" },
  AmazonS3: { name: "Amazon S3" },
  AmazonRedshift: { name: "Amazon Redshift" },
  MemcacheD: { name: "MemcacheD" },
  GraphDatabase: { name: "Graph Database" },
  APIGateway: { name: "API Gateway" },
  GraphQLAPI: { name: "GraphQL API" },
  DataLake: { name: "Data Lake" },
  DataWarehousing: { name: "Data Warehousing" },
  OLAP: { name: "OLAP" },
  OLTP: { name: "OLTP" },
  ColumnarDatabases: { name: "Columnar Databases" },
  AWSLambda: { name: "AWS Lambda" },
  GoogleBigtable: { name: "Google Bigtable" },
  AmazonDynamoDB: { name: "Amazon DynamoDB" },
  Docker: { name: "Docker" },
  Kubernetes: { name: "Kubernetes" },
  CICD: { name: "CI / CD" },
  CircleCI: { name: "CircleCI" },
  GitHubActions: { name: "GitHub Actions" },
  GitLabCI: { name: "GitLab CI" },
  Jenkins: { name: "Jenkins" },
  TravisCI: { name: "Travis CI" },
  AWS: { name: "AWS" },
  GoogleCloud: { name: "Google Cloud" },
  Azure: { name: "Azure" },
  ElasticBeanstalk: { name: "Elastic Beanstalk" },
  CloudFormation: { name: "CloudFormation" },
  Terraform: { name: "Terraform" },
  Pulumi: { name: "Pulumi" },
  Helm: { name: "Helm" },
  AWSECS: { name: "AWS ECS" },
  AWSEKS: { name: "AWS EKS" },
  Serverless: { name: "Serverless" },
  Fargate: { name: "Fargate" },
  Vercel: { name: "Vercel" },
  Netlify: { name: "Netlify" },
  Heroku: { name: "Heroku" },
  DigitalOcean: { name: "DigitalOcean" },
  Cloudflare: { name: "Cloudflare" },
  Packer: { name: "Packer" },
  Ansible: { name: "Ansible" },
  Bamboo: { name: "Bamboo" },
  OpenShift: { name: "OpenShift" },
  AmazonEC2: { name: "Amazon EC2" },
  AmazonCloudFront: { name: "Amazon CloudFront" },
  AWSFargate: { name: "AWS Fargate" },
  GoogleKubernetesEngine: { name: "Google Kubernetes Engine (GKE)" },
  RESTAPI: { name: "REST API" },
  gRPC: { name: "gRPC" },
  APIDocumentation: { name: "API Documentation" },
  Swagger: { name: "Swagger" },
  OpenAPI: { name: "OpenAPI" },
  OAuth: { name: "OAuth" },
  JWTTokens: { name: "JWT Tokens" },
  RateLimiting: { name: "Rate Limiting" },
  Webhooks: { name: "Webhooks" },
  Microservices: { name: "Microservices" },
  ServerlessArchitecture: { name: "Serverless Architecture" },
  Containerization: { name: "Containerization" },
  MessageQueues: { name: "Message Queues" },
  RabbitMQ: { name: "RabbitMQ" },
  Kafka: { name: "Kafka" },
  NATS: { name: "NATS" },
  AzureFunctions: { name: "Azure Functions" },
  AzureLogicApps: { name: "Azure Logic Apps" },
  AWSStepFunctions: { name: "AWS Step Functions" },
  CloudFunctions: { name: "Cloud Functions" },
  ApachePulsar: { name: "Apache Pulsar" },
  JWT: { name: "JWT" },
  Auth0: { name: "Auth0" },
  PassportJS: { name: "Passport.js" },
  Clerk: { name: "Clerk" },
  FirebaseAuth: { name: "Firebase Auth" },
  SingleSignOn: { name: "Single Sign-On (SSO)" },
  MultiFactorAuthentication: { name: "Multi-Factor Authentication (MFA)" },
  IdentityManagement: { name: "Identity Management" },
  SessionManagement: { name: "Session Management" },
  RoleBasedAccessControl: { name: "Role-Based Access Control (RBAC)" },
  XSS: { name: "XSS" },
  SQLInjection: { name: "SQL Injection" },
  SecurityAudits: { name: "Security Audits" },
  WebApplicationFirewall: { name: "Web Application Firewall (WAF)" },
  CORS: { name: "CORS" },
  HelmetJS: { name: "Helmet.js" },
  OWASP: { name: "OWASP" },
  PenetrationTesting: { name: "Penetration Testing" },
  Encryption: { name: "Encryption" },
  PKI: { name: "PKI" },
  TLS: { name: "TLS" },
  SSL: { name: "SSL" },
  DataPrivacy: { name: "Data Privacy" },
  ZeroTrustSecurity: { name: "Zero Trust Security" },
  EndToEndTesting: { name: "End-to-End Testing" },
  Mocking: { name: "Mocking" },
  TestCoverage: { name: "Test Coverage" },
  LoadTesting: { name: "Load Testing" },
  PerformanceTesting: { name: "Performance Testing" },
  StaticAnalysis: { name: "Static Analysis" },
  ContinuousIntegration: { name: "Continuous Integration" },
  CodeCoverage: { name: "Code Coverage" },
  TestAutomation: { name: "Test Automation" },
  SeleniumWebDriver: { name: "Selenium WebDriver" },
  Cucumber: { name: "Cucumber" },
  BDD: { name: "BDD" },
  Testrail: { name: "Testrail" },
  BugTracking: { name: "Bug Tracking" },
  GoogleAnalytics: { name: "Google Analytics" },
  GoogleTagManager: { name: "Google Tag Manager" },
  Mixpanel: { name: "Mixpanel" },
  Amplitude: { name: "Amplitude" },
  Kissmetrics: { name: "Kissmetrics" },
  Matomo: { name: "Matomo" },
  AdobeAnalytics: { name: "Adobe Analytics" },
  HubSpot: { name: "HubSpot" },
  Marketo: { name: "Marketo" },
  Mailchimp: { name: "Mailchimp" },
  SendGrid: { name: "SendGrid" },
  Zapier: { name: "Zapier" },
  IFTTT: { name: "IFTTT" },
  ABTesting: { name: "A/B Testing" },
  Optimizely: { name: "Optimizely" },
  Unbounce: { name: "Unbounce" },
  Klaviyo: { name: "Klaviyo" },
  ConvertKit: { name: "ConvertKit" },
  GoogleOptimize: { name: "Google Optimize" },
  VWO: { name: "VWO" },
  SurveyMonkey: { name: "SurveyMonkey" },
  Litmus: { name: "Litmus" },
  Caniemail: { name: "Caniemail" },
  Segment: { name: "Segment" },
  Pardot: { name: "Pardot" },
  ActiveCampaign: { name: "ActiveCampaign" },
  Moosend: { name: "Moosend" },
  ClickFunnels: { name: "ClickFunnels" },
  Drip: { name: "Drip" },
  CustomerIO: { name: "Customer.io" },
  Omnisend: { name: "Omnisend" },
  SEO: { name: "SEO" },
  OnPageSEO: { name: "On-Page SEO" },
  OffPageSEO: { name: "Off-Page SEO" },
  TechnicalSEO: { name: "Technical SEO" },
  KeywordResearch: { name: "Keyword Research" },
  LinkBuilding: { name: "Link Building" },
  ContentMarketing: { name: "Content Marketing" },
  SocialMediaMarketing: { name: "Social Media Marketing" },
  FacebookAds: { name: "Facebook Ads" },
  InstagramAds: { name: "Instagram Ads" },
  LinkedInAds: { name: "LinkedIn Ads" },
  GoogleAds: { name: "Google Ads" },
  TwitterAds: { name: "Twitter Ads" },
  TikTokAds: { name: "TikTok Ads" },
  PinterestAds: { name: "Pinterest Ads" },
  InfluencerMarketing: { name: "Influencer Marketing" },
  ContentStrategy: { name: "Content Strategy" },
  ContentCreation: { name: "Content Creation" },
  Blogging: { name: "Blogging" },
  VideoMarketing: { name: "Video Marketing" },
  LeadGeneration: { name: "Lead Generation" },
  LeadNurturing: { name: "Lead Nurturing" },
  PPC: { name: "PPC" },
  CPC: { name: "CPC" },
  CPA: { name: "CPA" },
  CPM: { name: "CPM" },
  AffiliateMarketing: { name: "Affiliate Marketing" },
  ReferralPrograms: { name: "Referral Programs" },
  InfluencerOutreach: { name: "Influencer Outreach" },
  CampaignManagement: { name: "Campaign Management" },
  SocialMediaStrategy: { name: "Social Media Strategy" },
  SocialMediaAnalytics: { name: "Social Media Analytics" },
  TikTokMarketing: { name: "TikTok Marketing" },
  YouTubeMarketing: { name: "YouTube Marketing" },
  CRM: { name: "CRM" },
  HubSpotCRM: { name: "HubSpot CRM" },
  Salesforce: { name: "Salesforce" },
  ZohoCRM: { name: "Zoho CRM" },
  Intercom: { name: "Intercom" },
  Zendesk: { name: "Zendesk" },
  Freshdesk: { name: "Freshdesk" },
  PandaDoc: { name: "PandaDoc" },
  Asana: { name: "Asana" },
  Trello: { name: "Trello" },
  Slack: { name: "Slack" },
  LeadScoring: { name: "Lead Scoring" },
  CustomerJourneys: { name: "Customer Journeys" },
  CustomerRetention: { name: "Customer Retention" },
  SalesFunnels: { name: "Sales Funnels" },
  EmailCampaigns: { name: "Email Campaigns" },
  EmailMarketing: { name: "Email Marketing" },
  SMSMarketing: { name: "SMS Marketing" },
  CustomerSegmentation: { name: "Customer Segmentation" },
  MarketingAutomation: { name: "Marketing Automation" },
  Retargeting: { name: "Retargeting" },
  ChurnRate: { name: "Churn Rate" },
  WordPress: { name: "WordPress" },
  Shopify: { name: "Shopify" },
  WooCommerce: { name: "WooCommerce" },
  Magento: { name: "Magento" },
  BigCommerce: { name: "BigCommerce" },
  Squarespace: { name: "Squarespace" },
  Webflow: { name: "Webflow" },
  Odoo: { name: "Odoo" },
  HeadlessCMS: { name: "Headless CMS" },
  Contentful: { name: "Contentful" },
  Prismic: { name: "Prismic" },
  Strapi: { name: "Strapi" },
  SalesforceCommerceCloud: { name: "Salesforce Commerce Cloud" },
  ShopifyPlus: { name: "Shopify Plus" },
  ShopifyAPI: { name: "Shopify API" },
  WooCommerceAPI: { name: "WooCommerce API" },
  ContentfulCMS: { name: "Contentful CMS" },
  BigCommerceAPI: { name: "BigCommerce API" },
  WebShop: { name: "WebShop" },
  eCommerce: { name: "eCommerce" },
  PaymentGateways: { name: "Payment Gateways" },
  Stripe: { name: "Stripe" },
  PayPal: { name: "PayPal" },
  Square: { name: "Square" },
  Braintree: { name: "Braintree" },
  CoinbaseCommerce: { name: "Coinbase Commerce" },
  AmazonPayments: { name: "Amazon Payments" },
  WooCommerceSubscriptions: { name: "WooCommerce Subscriptions" },
  ShopifyPayments: { name: "Shopify Payments" },
  Tableau: { name: "Tableau" },
  PowerBI: { name: "PowerBI" },
  Looker: { name: "Looker" },
  ModeAnalytics: { name: "Mode Analytics" },
  D3JS: { name: "D3.js" },
  Plotly: { name: "Plotly" },
  ChartJS: { name: "Chart.js" },
  Highcharts: { name: "Highcharts" },
  DataAnalysis: { name: "Data Analysis" },
  DataVisualization: { name: "Data Visualization" },
  GoogleDataStudio: { name: "Google Data Studio" },
  Excel: { name: "Excel" },
  GoogleSheets: { name: "Google Sheets" },
  MicrosoftPowerPoint: { name: "Microsoft PowerPoint" },
  BusinessIntelligence: { name: "Business Intelligence (BI)" },
  GoogleBigQuery: { name: "Google BigQuery" },
  SQLReporting: { name: "SQL Reporting" },
  KPIDashboards: { name: "KPI Dashboards" },
  ETLTools: { name: "ETL Tools" },
  AI: { name: "AI" },
  MachineLearning: { name: "Machine Learning" },
  DeepLearning: { name: "Deep Learning" },
  NaturalLanguageProcessing: { name: "Natural Language Processing (NLP)" },
  TensorFlow: { name: "TensorFlow" },
  PyTorch: { name: "PyTorch" },
  Keras: { name: "Keras" },
  MLOps: { name: "ML Ops" },
  SciPy: { name: "SciPy" },
  NumPy: { name: "NumPy" },
  OpenAI: { name: "OpenAI" },
  GPT3: { name: "GPT-3" },
  StableDiffusion: { name: "Stable Diffusion" },
  DALLE: { name: "DALL-E" },
  BERT: { name: "BERT" },
  XLNet: { name: "XLNet" },
  XGBoost: { name: "XGBoost" },
  RandomForest: { name: "Random Forest" },
  ReinforcementLearning: { name: "Reinforcement Learning" },
  NeuralNetworks: { name: "Neural Networks" },
  AIModels: { name: "AI Models" },
  AIAlgorithms: { name: "AI Algorithms" },
  ArtificialNeuralNetworks: { name: "Artificial Neural Networks" },
  ComputerVision: { name: "Computer Vision" },
  ConvolutionalNeuralNetworks: { name: "Convolutional Neural Networks (CNNs)" },
  Blockchain: { name: "Blockchain" },
  Ethereum: { name: "Ethereum" },
  Web3: { name: "Web3" },
  DecentralizedFinance: { name: "Decentralized Finance (DeFi)" },
  dApp: { name: "dApp" },
  IPFS: { name: "IPFS" },
  NFTs: { name: "NFTs" },
  Solana: { name: "Solana" },
  Polkadot: { name: "Polkadot" },
  Cryptocurrency: { name: "Cryptocurrency" },
  Metamask: { name: "Metamask" },
  Truffle: { name: "Truffle" },
  Infura: { name: "Infura" },
  Metaplex: { name: "Metaplex" },
  Web3JS: { name: "Web3.js" },
  Web3Development: { name: "Web3 Development" },
  EthersJS: { name: "Ethers.js" },
  DecentralizedIdentity: { name: "Decentralized Identity" },
  DAO: { name: "DAO" },
  Ethereum2: { name: "Ethereum 2.0" },
  Layer2Solutions: { name: "Layer 2 Solutions" },
  ZKRollups: { name: "ZK-Rollups" },
  Chainlink: { name: "Chainlink" },
  Oracles: { name: "Oracles" },
  NFTMarketplaces: { name: "NFT Marketplaces" },
  Bitcoin: { name: "Bitcoin" },
  ETL: { name: "ETL" },
  DataPipelines: { name: "Data Pipelines" },
  ApacheKafka: { name: "Apache Kafka" },
  ApacheSpark: { name: "Apache Spark" },
  Airflow: { name: "Airflow" },
  Flink: { name: "Flink" },
  Hadoop: { name: "Hadoop" },
  HDFS: { name: "HDFS" },
  Pig: { name: "Pig" },
  Hive: { name: "Hive" },
  ApacheStorm: { name: "Apache Storm" },
  Kinesis: { name: "Kinesis" },
  Databricks: { name: "Databricks" },
  BigData: { name: "Big Data" },
  DataLakes: { name: "Data Lakes" },
  ClickHouse: { name: "ClickHouse" },
  Iceberg: { name: "Iceberg" },
  GoogleCloudFunctions: { name: "Google Cloud Functions" },
  EventDrivenArchitecture: { name: "Event-Driven Architecture" },
  CloudEvent: { name: "Cloud Event" },
  CQRS: { name: "CQRS" },
  EventSourcing: { name: "Event Sourcing" },
};

// No need for skillRegex or skillAliasMap with spaCy